name: ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - uses: actions/checkout@v3
        with:
          repository: fapi-search/fapi-search.github.io
          path: fapi-search.github.io
          token: ${{ secrets.GHP_DEPLOY_REPO_TOKEN }}
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - run: mkdocs gh-deploy --config-file ../mkdocs.yml --remote-branch main
        working-directory: fapi-search.github.io
